### ISSUE TITLE
Typos in quality questions

### ISSUE THREAD

**Issue by beth-e-jones** [best-practice-and-impact/analysis_project_documentation#1]
Typos to correct

Introduction page
- [x] Introduction: "The stages are covered by the following tabs on the website" to "the questions are..."
- [x] Correct AQuA spelling in "key Aqua roles..."
- [x] Introduction: Pressing Ctrl+S will automatically download a copy of the HTML page on your machine." to "will allow you to save a copy..."
- [x]  AQuA roles and responsibilities - change "creation" to "allocation"
- [x] AQuA roles and responsibilities - bullet points have not worked
- [x] Responsibilities of the Senior Responsible Owner: remove hyphen next to "signs off"
- [x] Responsibilities of Commissioner: remove "The Commissioner"

Quality questions: I. SCOPING

- [x]  Q1 (Why the questions matter): comma needed after "clear"
- [ ] Q15 (Why the questions matter): commas needed after "analysis" and "occurring"
- [x] Q19 (Why the questions matter): Remove full stop mid-sentence
- [x] Q8 (Code of Practice): Correct spelling of Chief
- [x]  Q17 (Code of Practice): Fix line break if possible
- [x] Q17 (Code of Practice): Remove capitalisation of "Producers"
- [x]  Q15 (AQuA): Inconsistent capitalisation of roles

Quality questions III: CONDUCTING AND CHECKING ANALYSIS
- [x]  Q30: Consider rephrasing of "do you think this would be helpful" to "if not, why not?"
- [x]  Q38 (why the questions matter): Correct spelling of externally
- [x] Q49 (why the questions matter): Correct spelling of assure
- [x]  Q33 (Code of Practice): Fix line break if possible

FAQs
- [x] Business critical numbering not formatted like numbered points
- [x] Bullet points for AQuA book roles haven't rendered properly
- [x]  Help available bullet points not rendered properly

**Comment by zarbspace** [comment]
Re-wrote Q15 to make it simpler.

**Comment by zarbspace** [comment]
Resolved
