### ISSUE TITLE
Rendering of quality questions post-CSS styles

### ISSUE THREAD

**Issue by beth-e-jones** [best-practice-and-impact/analysis_project_documentation#10]
Several small issues in rendering in the quality questions with the new structure:

- [x] Q22 Code of Practice: Line break in question that is inconsistent with other two tabs
- [x] Q36: split when rendering, so question number appears in the tab and the content is split across 2 rows
- [ ] 
![image](https://github.com/best-practice-and-impact/analysis_project_documentation/assets/128492906/4737e742-aa07-4068-a91b-67a23228459a)
![image](https://github.com/best-practice-and-impact/analysis_project_documentation/assets/128492906/d35f77ff-0959-4d66-9eb0-df27c8de3f31)

- [x] Q46: space needed between "you" and "should"
- [x] Q39: rendering misses question number so columns are offset 
![image](https://github.com/best-practice-and-impact/analysis_project_documentation/assets/128492906/d3afc5ae-6c75-498a-92b5-8febab4a9c63)

**Comment by zarbspace** [comment]
Resolved. These items now render correctly.
