### ISSUE TITLE
Quality questions: Sign-off by SRO

### ISSUE THREAD

**Issue by beth-e-jones** [best-practice-and-impact/analysis_project_documentation#2]
Currently documented as a Yes/No response for each question. Suggestion to change this to initials to clarify who has signed it off (particularly if SRO changes during lifecycle of a project)

Additionally, suggestion of some kind of line for commissioner, SRO, and analytical assurer to all confirm they have read this document and agree with the responses.

**Comment by zarbspace** [comment]
Modified form to include top-level signoff rather than point by point.
