### ISSUE TITLE
Quality questions: Q29

### ISSUE THREAD

**Issue by beth-e-jones** [best-practice-and-impact/analysis_project_documentation#4]
This may be better separated into 2 questions to reduce the risk of any one of these important questions being missed. Under importance, we should also add that analysts should not assume datasets are high quality and should conduct your own quality assurance on the data.

**Comment by zarbspace** [comment]
Introduced new Q30 which separates out the second part of Q29 "Do you understand how data providers collect, process and quality assure the data you use?". Updated and renumbered all subsequent questions and revised HTML question template accordingly.
