### ISSUE TITLE
Question: .gitignore quarto json, preview, and xref files

### ISSUE THREAD

**Issue by beth-e-jones** [best-practice-and-impact/analysis_project_documentation#8]
When merging, differences caused by rendering the quarto files create unnecessary merge conflicts which do not need to be reviewed. 
Can we put all the files that regenerate each time there is a render into a .gitignore to avoid this happening?

**Comment by zarbspace** [comment]
In a word no, because those files are what are published on Github.io. If we don't upload them, the website won't exist. It is rendered directly from the docs folder content, which is created when we render the Quarto files.
